version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/web/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/web/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/web/php/php.local.ini:/usr/local/etc/php/conf.d/php.local.ini
    environment:
      APP_ENV: ${APP_ENV}
    depends_on:
      - mysql
      - redis
    ports:
      - "${WEB_FORWARD_PORT:-80}:80"
    networks:
      - virta
  mysql:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_FORWARD_PORT:-3306}:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - virta
  redis:
    image: redis:6.2.6-alpine3.15
    restart: always
    sysctls:
      - net.core.somaxconn=10000
    ports:
      - "${REDIS_FORWARD_PORT:-6379}:6379"
    volumes:
      - redis:/data
    networks:
      - virta
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${MAILHOG_FORWARD_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_FORWARD_PORT:-8025}:8025'
    networks:
      - virta
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - './wiki:/var/www/html'
    ports:
      - '${FORWARD_SWAGGER_UI_PORT:-8080}:8080'
    environment:
      - SWAGGER_JSON=/var/www/html/swagger.yaml
    networks:
      - virta

  consumer:
    build:
      context: .
      dockerfile: ./docker/consumer/Dockerfile
    restart: always
    volumes:
      - ./consumer:/var/www/html
      - ./docker/consumer/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/consumer/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/consumer/php/php.local.ini:/usr/local/etc/php/conf.d/php.local.ini
    depends_on:
      - web
    ports:
      - "${CONSUMER_FORWARD_PORT:-8000}:80"
    networks:
      - virta

networks:
  virta:
    driver: bridge
volumes:
  mysql:
    driver: local
  redis:
    driver: local
