version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/web/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/web/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/web/php/php.local.ini:/usr/local/etc/php/conf.d/php.local.ini
    environment:
      APP_ENV: ${APP_ENV}
    networks:
      - default
    depends_on:
      - mysql
      - redis
    ports:
      - "${WEB_FORWARD_PORT:-80}:80"
  mysql:
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_FORWARD_PORT:-3306}:3306"
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis:6.2.6-alpine3.15
    restart: always
    sysctls:
      - net.core.somaxconn=10000
    volumes:
      - redis:/data

volumes:
  mysql:
  redis:
