version: "3.7"

x-environment: &web_default_variables
  APP_URL: ${APP_URL}
  APP_DEBUG: ${APP_DEBUG}
  APP_ENV: ${APP_ENV}
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_DATABASE: ${DB_DATABASE}
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  QUEUE_CONNECTION: ${QUEUE_CONNECTION}
  CACHE_DRIVER: ${CACHE_DRIVER}

  ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
  GRAYLOG_GELF_HOST: ${GRAYLOG_GELF_HOST}
  SENTRY_DSN: ${SENTRY_DSN}
  LOG_CHANNEL: ${LOG_CHANNEL}
  APP_SECURITY_TOKEN: ${APP_SECURITY_TOKEN}

services:
  web:
    image: ${WEB_IMAGE}
    environment:
      <<: *web_default_variables
      CONTAINER_ROLE: web
    ports:
      - "${WEB_FORWARD_PORT:-80}:80"
    volumes:
      - web_storage_logs:/var/www/html/storage/logs
    depends_on:
      - mysql
      - redis
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
      resources:
        limits:
          cpus: '1'
          memory: 2048M
  default_queue:
    image: ${WEB_IMAGE}
    volumes:
      - web_storage_logs:/var/www/html/storage/logs
    environment:
      <<: *web_default_variables
      CONTAINER_ROLE: queue
      QUEUE_NAME: default
    depends_on:
      - web
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
  product_sync_queue:
    image: ${WEB_IMAGE}
    volumes:
      - web_storage_logs:/var/www/html/storage/logs
    environment:
      <<: *web_default_variables
      CONTAINER_ROLE: queue
      QUEUE_NAME: product_sync
    depends_on:
      - web
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
  stock_sync_queue:
    image: ${WEB_IMAGE}
    volumes:
      - web_storage_logs:/var/www/html/storage/logs
    environment:
      <<: *web_default_variables
      CONTAINER_ROLE: queue
      QUEUE_NAME: stock_sync
    depends_on:
      - web
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
  status_sync_queue:
    image: ${WEB_IMAGE}
    volumes:
      - web_storage_logs:/var/www/html/storage/logs
    environment:
      <<: *web_default_variables
      CONTAINER_ROLE: queue
      QUEUE_NAME: status_sync
    depends_on:
      - web
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
  schedule:
    image: ${WEB_IMAGE}
    volumes:
      - web_storage_logs:/var/www/html/storage/logs
    environment:
      <<: *web_default_variables
      CONTAINER_ROLE: schedule
    depends_on:
      - web
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '3'
          memory: 2048M
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "${MYSQL_FORWARD_PORT:-3306}:3306"
    cap_add:
      - SYS_NICE
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
  redis:
    image: redis:6.2.6-alpine3.15
    sysctls:
      - net.core.somaxconn=10000
    volumes:
      - redis:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M

volumes:
  web_storage_logs:
  mysql:
  redis:
